version: '3.3'

services:
  lastseen-backend:
    volumes:
      - '.:/app'
    image: alissongaliza/lastseen:devel
    ports:
      - '4000:4000'
    environment:
      - TMDB_API_KEY

  lastseen-redis:
    image: redis:6.0.5-alpine
    ports:
      - '6379:6379'
